import type { LocalizedText } from '../../core/level-registry.js';
import type { Lang } from '../../core/units.js';

/**
 * UI chrome dictionary. Level copy lives in content/levels/*; this file holds
 * only interface strings, so no user-facing text ends up in scene code.
 * All three languages are required (docs/M0-design-plan.md §12).
 */
export const UI_STRINGS = {
  'app.title': {
    en: 'Car → Atom',
    ru: 'Car → Atom',
    uk: 'Car → Atom',
  },
  'app.tagline': {
    en: 'A car, taken apart down to an iron atom',
    ru: 'Автомобиль, разобранный до атома железа',
    uk: 'Автомобіль, розібраний до атома заліза',
  },
  'intro.title': {
    en: 'One continuous flight, from the whole car to a single atom',
    ru: 'Один непрерывный полёт — от машины целиком до одного атома',
    uk: 'Один безперервний політ — від автомобіля повністю до одного атома',
  },
  'intro.body': {
    en: 'No downloaded models or textures: every part is generated by code. Use the scale ruler, open a branch, and follow it down.',
    ru: 'Ни одной скачанной модели или текстуры: каждая деталь сгенерирована кодом. Смотрите на шкалу масштаба, открывайте ветку и спускайтесь по ней.',
    uk: 'Жодної завантаженої моделі чи текстури: кожна деталь згенерована кодом. Дивіться на шкалу масштабу, відкривайте гілку та спускайтеся нею.',
  },
  'intro.start': {
    en: 'Start the flight',
    ru: 'Начать полёт',
    uk: 'Почати політ',
  },
  'intro.guide': {
    en: 'Read the text guide instead',
    ru: 'Читать текстовый гайд',
    uk: 'Читати текстовий гайд',
  },
  'ui.prev': { en: 'Zoom out one level', ru: 'На уровень выше', uk: 'На рівень вище' },
  'ui.next': { en: 'Zoom in one level', ru: 'На уровень глубже', uk: 'На рівень глибше' },
  'ui.reset': { en: 'Reset view', ru: 'Сбросить вид', uk: 'Скинути вигляд' },
  'ui.play': { en: 'Play', ru: 'Играть', uk: 'Грати' },
  'ui.pause': { en: 'Pause', ru: 'Пауза', uk: 'Пауза' },
  'ui.honesty.title': {
    en: 'How accurate is this?',
    ru: 'Насколько это точно?',
    uk: 'Наскільки це точно?',
  },
  'ui.honesty.close': { en: 'Close', ru: 'Закрыть', uk: 'Закрити' },
  'ui.honesty.official': {
    en: 'From public OEM and reference data',
    ru: 'Из публичных данных производителя и справочников',
    uk: 'З публічних даних виробника та довідників',
  },
  'ui.honesty.schematic': {
    en: 'Schematic / deliberately simplified',
    ru: 'Схематично / сознательно упрощено',
    uk: 'Схематично / свідомо спрощено',
  },
  'ui.honesty.sources': { en: 'Sources', ru: 'Источники', uk: 'Джерела' },
  'ui.honesty.unverified': {
    en: 'Needs verification',
    ru: 'Требует проверки',
    uk: 'Потребує перевірки',
  },
  'ui.honesty.disclaimer': {
    en: 'Internal geometry is schematic and is not a copy of OEM parts. Public specifications are engineering popularisation, not a repair manual.',
    ru: 'Внутренняя геометрия схематична и не является копией OEM-деталей. Публичные ТТХ — инженерная популяризация, а не руководство по ремонту.',
    uk: 'Внутрішня геометрія схематична й не є копією OEM-деталей. Публічні ТТХ — інженерна популяризація, а не посібник із ремонту.',
  },
  'ui.scale': { en: 'Scale', ru: 'Масштаб', uk: 'Масштаб' },
  'ui.facts': { en: 'Physics', ru: 'Физика', uk: 'Фізика' },
  'ui.callouts': { en: 'Numbers', ru: 'Числа', uk: 'Числа' },
  'ui.subject': { en: 'What you see', ru: 'Что перед вами', uk: 'Що перед вами' },
  'ui.animation': { en: 'Animation', ru: 'Анимация', uk: 'Анімація' },
  'ui.geometry': { en: 'How it is built', ru: 'Как построено', uk: 'Як побудовано' },
  'ui.mode.tour': { en: 'Tour', ru: 'Тур', uk: 'Тур' },
  'ui.mode.explore': { en: 'Explore', ru: 'Осмотр', uk: 'Огляд' },
  'ui.mode.cutaway': { en: 'Cutaway', ru: 'Разрез', uk: 'Розріз' },
  'ui.mode.explode': { en: 'Explode', ru: 'Разлёт', uk: 'Розліт' },
  'ui.mode.flow': { en: 'Flow', ru: 'Потоки', uk: 'Потоки' },
  'ui.mode.slowmo': { en: 'Slow-mo', ru: 'Слоу-мо', uk: 'Слоу-мо' },
  'ui.mode.compare': { en: 'Compare', ru: 'Сравнить', uk: 'Порівняти' },
  'ui.mode.dyno': { en: 'Dyno', ru: 'Динамометр', uk: 'Динамометр' },
  'ui.help': { en: 'Help', ru: 'Справка', uk: 'Довідка' },
  'ui.language': { en: 'Language', ru: 'Язык', uk: 'Мова' },
  'ui.scaleRuler': { en: 'Scale ruler', ru: 'Линейка масштаба', uk: 'Лінійка масштабу' },
  'ui.anchor.car': { en: 'car', ru: 'машина', uk: 'машина' },
  'ui.anchor.wheel': { en: 'wheel', ru: 'колесо', uk: 'колесо' },
  'ui.anchor.hand': { en: 'palm', ru: 'ладонь', uk: 'долоня' },
  'ui.anchor.coin': { en: 'coin', ru: 'монета', uk: 'монета' },
  'ui.anchor.tooth': { en: 'gear tooth', ru: 'зуб шестерни', uk: 'зуб шестерні' },
  'ui.anchor.hair': { en: 'a human hair', ru: 'толщина волоса', uk: 'товщина волосини' },
  'ui.anchor.cell': { en: 'red blood cell', ru: 'эритроцит', uk: 'еритроцит' },
  'ui.anchor.film': { en: 'oil film', ru: 'масляная плёнка', uk: 'масляна плівка' },
  'ui.anchor.atom': { en: 'iron atom', ru: 'атом железа', uk: 'атом заліза' },
  'a11y.levelChanged': {
    en: 'Level: {title}. Scale: {scale}.',
    ru: 'Уровень: {title}. Масштаб: {scale}.',
    uk: 'Рівень: {title}. Масштаб: {scale}.',
  },
  'a11y.modeChanged': {
    en: 'Mode: {mode}.',
    ru: 'Режим: {mode}.',
    uk: 'Режим: {mode}.',
  },
  'a11y.honestyOpen': {
    en: 'Accuracy panel opened.',
    ru: 'Панель «Насколько это точно?» открыта.',
    uk: 'Панель «Наскільки це точно?» відкрита.',
  },
  'a11y.webglMissing': {
    en: 'WebGL is unavailable; showing the text guide.',
    ru: 'WebGL недоступен; показываем текстовый гайд.',
    uk: 'WebGL недоступний; показуємо текстовий гайд.',
  },
} as const satisfies Record<string, LocalizedText>;

export type UIKey = keyof typeof UI_STRINGS;

export interface Interpolation {
  [key: string]: string | number;
}

/** Looks up a UI string and replaces `{placeholder}` tokens. */
export function t(key: UIKey, lang: Lang, params?: Interpolation): string {
  const entry: LocalizedText = UI_STRINGS[key];
  const template = entry[lang] || entry.en;
  if (!params) return template;
  return template.replace(/\{(\w+)\}/g, (_match, name: string) => {
    const value = params[name];
    return value === undefined ? `{${name}}` : String(value);
  });
}

export const LANG_NAMES: Record<Lang, LocalizedText> = {
  en: { en: 'English', ru: 'Английский', uk: 'Англійська' },
  ru: { en: 'Russian', ru: 'Русский', uk: 'Російська' },
  uk: { en: 'Ukrainian', ru: 'Украинский', uk: 'Українська' },
};
